import { Dimensions, StyleSheet } from "react-native";
import Constants from "expo-constants";
import color from "./color";

const stylesRegister = StyleSheet.create({
  container: {
    width: "100%",
    flex: 1,
    backgroundColor: "white",
    justifyContent: "space-between",
  },
  loginContainer: {
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: "white",
    elevation: 20,
    shadowColor: "grey",
    shadowOpacity: 0.5,
    shadowRadius: 1,
    shadowOffset: {
      width: 5,
      height: 5,
    },
    padding: 13,
  },
  loginInputContainer: {
    flexDirection: "row",
    borderColor: color.primary,
    borderBottomWidth: 1,
  },
  loginInput: {
    flex: 1,
    padding: 5,
  },

  loginTextTopContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginLeft: 20,
    marginTop: Constants.statusBarHeight * 1.5,
    marginBottom: 15,
  },
  circleContainer: {
    flexDirection: "row",
    alignItems: "center",
    left: 25,
  },
  loginTextTopContainerSmallCircle: {
    width: 35,
    height: 35,
    borderRadius: 20,
    backgroundColor: color.primary,
    elevation: 17,
    shadowColor: "grey",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 30,
    marginRight: 20,
  },
  loginTextTopContainerBigCircle: {
    width: 70,
    height: 70,
    borderRadius: 40,
    backgroundColor: color.primary,
    elevation: 25,
    shadowColor: "grey",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 30,
  },
  icon: {
    alignSelf: "center",
    paddingRight: 5,
  },
  submitButton: {
    backgroundColor: color.primary,
    left: "60%",
    paddingLeft: "10%",
    marginTop: 25,
    borderRadius: 25,
    width: "60%",
    elevation: 5,
    shadowColor: "grey",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 30,
  },
  submitButtonText: {
    color: "white",
    padding: 10,
    fontWeight: "bold",
    marginBottom: 5,
  },
  buttonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  loginTextBottomContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 20,
    marginRight: 20,
    bottom: 25,
    marginTop: 10,
  },
  loginTextBottomContainerBigCircle: {
    width: 70,
    height: 70,
    borderRadius: 40,
    backgroundColor: color.primary,
    elevation: 20,
    shadowColor: "grey",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 30,
    left: -50,
  },
  loginTextBottomContainerSmallCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: color.primary,
    elevation: 15,
    shadowColor: "grey",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 30,
    right: 27,
  },
  googleLogin: {
    flexDirection: "row",
    backgroundColor: "white",
    justifyContent: "space-between",
    borderRadius: 50,
    elevation: 5,
    shadowColor: "grey",
    shadowOpacity: 0.5,
    shadowRadius: 30,
    shadowOffset: {
      width: 5,
      height: 5,
    },
  },
  fbLogin: {
    flexDirection: "row",
    backgroundColor: "#326ba8",
    justifyContent: "space-between",
    borderRadius: 50,
    marginLeft: 20,
    elevation: 5,
    shadowColor: "grey",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 30,
  },
  loginText: {
    fontSize: 25,
    fontWeight: "bold",
    marginLeft: 5,
    fontFamily: "monospace",
  },
  signupText: {
    fontSize: 25,
    fontWeight: "bold",
    marginLeft: 90,
    fontFamily: "monospace",
    textDecorationLine: "underline",
    top: 5,
  },
  profileContainer: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
  },
  productContainer: {
    flexDirection: "row",
    borderColor: color.primary,
    borderBottomWidth: 1,
  },
  profilePic: {
    alignSelf: "center",
    borderRadius: 20,
    width: 120,
    height: 120,
    overflow: "hidden",
    marginBottom: 10,
  },
});

export default stylesRegister;
